config/routes.rb
BillsApp::Application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}, path_prefix: 'my'
  
  resources :users
 
  resources :line_items

  resources :bills do
    resources :line_items
    member do
      get 'change_status'
    end
     member do
      get 'change_status_failed'
    end
    collection do
      get 'need_checkout'
     end
  end

   root 'bills#index', root: 'bills'
   
   get 'users' => 'users#index'

  

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :line_items, dependent: :destroy 
  belongs_to :user

  validates :name, :limit_date, :status, presence: true
 
  Status = %w[Uncategorized Waiting Paid]
  def total_price
    line_items.to_a.sum{ |item| item.price}
  end

  def change_status(status)
   	self.status = status
   	save
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    respond_to do |format|
      if @bill.nil?
        format.html { redirect_to @bill, notice: 'Bill is empty' }
      else
        format.html { redirect_to bill_line_items_path(@bill), notice: 'Bill contains: ' }
      end
    end
  end

  # GET /bills/new
  def new
    authorize! :manage, Bill
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    authorize! :manage, Bill
    @bill = Bill.new(bill_params)
    @bill.author = current_user.email
    respond_to do |format|
      if @bill.save
        format.html { redirect_to new_bill_line_item_path(@bill), notice: 'Bill was successfully created.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bills_path, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    authorize! :manage, Bill
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end

  def change_status
    @bill = Bill.find(params[:id])
    @bill.change_status('Paid')
    respond_to do |format|
      format.html { redirect_to bills_path, notice: 'Checkout successfully.' }
    end
  end

  def change_status_failed
    @bill = Bill.find(params[:id])
    @bill.change_status('Payment Failed')
    respond_to do |format|
      format.html { redirect_to bills_path, notice: 'Checkout Failed.' }
    end
  end

  def need_checkout
    @bills = Bill.all
    @bills_wait = @bills.where(status: 'Waiting')
    # @bills_proc = @bills.where(status: 'Processing')
    # @bills_proc.order('bills.updated_at DESC ')
    @bills_wait.order('bills.updated_at DESC ')
    # .map{|b| {id: b.id}}
    render json: @bills_wait.pluck(:id)
    if @bills_wait.any?
      if@bills_wait[0].status == 'Waiting'
        @bills_wait[0].status = 'Processing'
        @bills_wait[0].save
      end
    # elsif @bills_proc.any?
    #   @bills_proc.each do |bill|
    #     if bill.status == 'Processing'
    #       bill.status = 'Payment Failed'
    #       bill.save
    #     end
    #   end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bill
    @bill = Bill.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bill_params
    params.require(:bill).permit(:name, :author, :limit_date, :status)
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
 
  <div class="field">
    <%= f.label :limit_date %><br>
    <%= f.date_select :limit_date %>
  </div>
   
  <div class="field">
    <%= f.label :status %><br>
    <%= f.collection_select :status, Bill::Status, :to_s, :titleize %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<% if flash[:error] %>
<p class = "error"><%= flash[:error] %></p>
<% end %> 


<h1>Bills</h1>

<table align="center" >
  <thead>
    <tr >
      <th>Name</th>
      <th>Author</th>
      <th>Limit date</th>
      <th>Total Price</th>
      <th>Status</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.name %></td>
        <td><%= bill.author %></td>
        <td><%= bill.limit_date %></td>
        <td><%= number_to_currency(bill.total_price) %></td>
        <td><%= bill.status %></td>
        <td><%= link_to 'Show', bill %></td>
        <% if can? :update, @bill %>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <% end %>
        <% if can? :destroy, @bill %>
        <td><%= link_to 'Remove', bill, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </td>
        <% if(bill.status != 'Paid')&&(can? :update, @bill) %>
          <td><%= link_to 'Checkout', change_status_bill_path(bill.id) %>
        <% end %>
        </td>
       </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, @bill %>
<%= link_to 'New Bill', new_bill_path %>
<% end %>

app/views/bills/new.html.erb
<h1>New bill</h1>
<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bill.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @bill.author %>
</p>

<p>
  <strong>Limit date:</strong>
  <%= @bill.limit_date %>
</p>


<p>
  <strong>Status</strong>
  <%= @bill.status %>
</p>


<% if can? :update, @bill %>
<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>