config/routes.rb
BillsApp::Application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}, path_prefix: 'my'
  
  resources :users
 
  resources :line_items

  resources :bills do
    resources :line_items
    member do
      get 'change_status'
    end
     member do
      get 'change_status_failed'
    end
    collection do
      get 'need_checkout'
     end
  end

   root 'bills#index', root: 'bills'
   
   get 'users' => 'users#index'

  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :bill

  validates :title, :description, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.10}
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @bill = Bill.find(params[:bill_id])
    @line_items = @bill.line_items
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @bill = Bill.find(params[:bill_id])

    @line_item = @bill.line_items.build
    authorize! :update, LineItem
  end

  # GET /line_items/1/edit
  def edit
    authorize! :update, LineItem
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params.merge(bill_id: params[:bill_id]))
    authorize! :create, LineItem
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to bills_path, notice: 'Item was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    authorize! :update, LineItem
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to bills_path, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    authorize! :destroy, LineItem
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to bill_path(@line_item.bill_id) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def line_item_params
    params.require(:line_item).permit(:title, :description, :price, :bill_id)
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for [@bill, @line_item]  do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_line_items_path(@line_item.bill_id, @line_item) %>

app/views/line_items/index.html.erb
<h1>Items</h1>

<table align="center">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Created by</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.title %></td>
        <td><%= line_item.description %></td>
        <td><%= line_item.price %></td>
        <td><%= line_item.bill.author %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Remove', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New item', new_bill_line_item_path %>

app/views/line_items/new.html.erb
<h1>Add item to bill</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @line_item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @line_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @line_item.price %>
</p>


<%= link_to 'Edit', edit_line_item_path%> |
<%= link_to 'Back', bill_line_items_path(@line_item.bill_id, @line_item)%>